name: example-environment
channels:
  - conda-forge
dependencies:
  - python=3.11
  - cv2
  - numpy
  - openai
  - os
  - PIL
  - psutil
  - toolz
  - matplotlib
  - subprocess
  - dill
  - pandas
  - partd
  - bokeh
  - dask
