name: example-environment
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - opencv
  - pillow
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - dask
  - pip
  - pip:
      - openai
